name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        required: true
        type: choice
        options:
          - dev

jobs:
  e2e:
    uses: ./.github/workflows/e2e-base.yml
    with:
      environment: ${{ inputs.environment }}
